import { CodeLanguage } from "../constants/languages";

export function getSuggestedTagsByLanguage(language: CodeLanguage): string[] {
  const commonTags = [
    "utils",
    "helpers",
    "algorithm",
    "data-structure",
    "regex",
    "validation",
    "authentication",
    "authorization",
    "security",
    "performance",
    "optimization",
    "testing",
    "debug",
    "error-handling",
    "example",
    "snippet",
    "boilerplate",
    "template",
  ];

  const languageSpecificTags: Record<CodeLanguage, string[]> = {
    javascript: [
      "react",
      "vue",
      "angular",
      "nextjs",
      "nodejs",
      "express",
      "es6",
      "async",
      "promise",
      "async-await",
      "hooks",
      "api",
      "rest",
      "graphql",
      "dom",
      "event",
      "callback",
      "closure",
      "prototype",
      "class",
    ],
    typescript: [
      "react",
      "vue",
      "angular",
      "nextjs",
      "nodejs",
      "express",
      "interface",
      "type",
      "generic",
      "decorator",
      "async",
      "promise",
      "hooks",
      "api",
      "rest",
      "graphql",
    ],
    python: [
      "django",
      "flask",
      "fastapi",
      "pandas",
      "numpy",
      "matplotlib",
      "requests",
      "async",
      "decorator",
      "class",
      "generator",
      "list-comprehension",
      "api",
      "rest",
      "data-science",
      "machine-learning",
    ],
    java: [
      "spring",
      "spring-boot",
      "maven",
      "gradle",
      "jpa",
      "hibernate",
      "servlet",
      "jdbc",
      "api",
      "rest",
      "class",
      "interface",
      "annotation",
      "exception",
    ],
    c: [
      "pointer",
      "memory",
      "struct",
      "function",
      "array",
      "string",
      "algorithm",
      "system-programming",
    ],
    cpp: [
      "class",
      "template",
      "stl",
      "pointer",
      "memory",
      "smart-pointer",
      "algorithm",
      "oop",
    ],
    go: [
      "goroutine",
      "channel",
      "interface",
      "package",
      "api",
      "rest",
      "concurrency",
      "microservice",
    ],
    rust: [
      "ownership",
      "borrowing",
      "lifetime",
      "trait",
      "pattern-matching",
      "async",
      "cargo",
      "memory-safety",
    ],
    php: [
      "laravel",
      "symfony",
      "composer",
      "api",
      "rest",
      "database",
      "orm",
      "mvc",
    ],
    html: [
      "semantic",
      "form",
      "table",
      "accessibility",
      "seo",
      "responsive",
      "component",
    ],
    css: [
      "flexbox",
      "grid",
      "animation",
      "responsive",
      "scss",
      "sass",
      "tailwind",
      "bootstrap",
      "component",
    ],
    json: [
      "api",
      "config",
      "data",
      "schema",
      "validation",
    ],
    markdown: [
      "documentation",
      "readme",
      "github",
      "formatting",
    ],
  };

  const specificTags = languageSpecificTags[language] || [];
  
  return [...specificTags, ...commonTags];
}
